---
name: CI

'on':
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:

  yaml-lint:git@codeberg.org:hertg/role-add-sudo-user.git
    name: Run YAML Lint
    uses: ./.forgejo/workflows/run-yaml-lint.yml
    runs-on: selfhosted

  ansible-lint:
    name: Run Ansible Lint
    uses: ./.forgejo/workflows/run-ansible-lint.yml
    runs-on: selfhosted
