---

name: Run Linter

'on':
  workflow_call:

jobs:
  yaml-lint:
    name: YAML Lint
    runs-on: docker
    steps:

      - name: Checkout
        uses: https://code.forgejo.org/actions/checkout@v4

      - name: Run yamllint
        uses: https://code.forgejo.org/ansible-actions/yamllint-action@v0.0.2
        with:
          target: "./"

      - name: Install ansible-lint
        run: |
          apt update
          apt install -y --no-install-recommends ansible-lint

      - name: Run ansible-lint
        run: ansible-lint .

  ansible-lint:
    name: Ansible Lint
    runs-on: docker
    steps:

      - name: Checkout
        uses: https://code.forgejo.org/actions/checkout@v4

      - name: Install ansible-lint
        run: |
          apt update
          apt install -y --no-install-recommends ansible-lint

      - name: Run ansible-lint
        run: ansible-lint .
