---

- name: Check for supported distro
  when: ansible_distribution != 'Debian' and ansible_distribution != 'Ubuntu'
  ansible.builtin.fail: >
    "{{ ansible_distribution }} is unsupported. Only Debian and Ubuntu."

- name: Install sudo package
  ansible.builtin.apt:
    name: sudo
    state: present

- name: Create sudoers group '{{ sudo_group_name }}'
  ansible.builtin.group:
    name: "{{ sudo_group_name }}"
    state: present

- name: Allow sudo access for sudoers group
  when: not passwordless_sudo
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%{{ sudo_group_name }}'
    line: '%{{ sudo_group_name }} ALL=(ALL:ALL) ALL'
    validate: 'visudo -cf %s'

- name: Allow passwordless sudo access for sudoers group
  when: passwordless_sudo
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%{{ sudo_group_name }}'
    line: '%{{ sudo_group_name }} ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: Create user '{{ user_name }}'
  ansible.builtin.user:
    name: "{{ user_name }}"
    groups: "{{ sudo_group_name }}"
    shell: '/bin/bash'
    password: >
      "{{ '*' if user_password is not defined
      else (user_password | password_hash('sha512'))
      }}"
    update_password: on_create
    append: true
    state: present
    createhome: true
  no_log: true

- name: Add to sudoers group
  when: user_name is defined and sudo_group_name is defined
  ansible.builtin.user:
    name: "{{ user_name }}"
    groups: "{{ sudo_group_name }}"
    append: true

- name: Set authorized keys for new user
  when: authorized_keys is defined
  ansible.posix.authorized_key:
    user: "{{ user_name }}"
    state: present
    key: "{{ authorized_keys }}"

# - name: Update for user .bashrc
#   when: user_name is defined
#   copy:
#     src: files/.bashrc
#     dest: /home/{{ user_name }}/.bashrc
#     owner: "{{ user_name }}"
#     group: "{{ user_name }}"
#     mode: 0644

- name: Create .hushlogin for user (suppress ssh motd)
  when: user_name is defined
  ansible.builtin.copy:
    content: ""
    dest: /home/{{ user_name }}/.hushlogin
    force: false
    group: "{{ user_name }}"
    owner: "{{ user_name }}"
    mode: "0644"

- name: Update root password
  when: not disable_root and root_password is defined
  ansible.builtin.user:
    name: root
    password: "{{ root_password | password_hash('sha512') }}"

- name: Disable root login
  when: disable_root
  ansible.builtin.user:
    name: root
    password: "*"
